apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking-api
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      app: tracking-api
  template:

    metadata:

      annotations:
        ad.datadoghq.com/tracking-api.logs: '[{"source": "kubernetes", "service": "tracking-api", "env": "dev"}]'
        ad.datadoghq.com/tracking-api.apm: '[{"service_name": "tracking-api", "env": "dev"}]'
      labels:
        app: tracking-api
    spec:

      imagePullSecrets:
        - name: scw-registry-secret
      containers:
        - name: tracking-api
          image: rg.fr-par.scw.cloud/goodfood/tracking-api:dev
          ports:
            - containerPort: 8080
          env:
            - name: Env
              value: dev
            - name: APIPort
              value: ":8080"
            - name: DBHost
              value: "db-service" # Mettez l'adresse correcte ici
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
