apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracking-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goodfoodcesi/tracking-api.git
    targetRevision: HEAD
    path: kube
  destination:
    server: https://kubernetes.default.svc
    namespace: tracking-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
