name: CI/CD

on: [ push ]

env:
  REGISTRY: ${{ secrets.REGISTRY }}
  REGISTRY_NAMESPACE: ${{ secrets.SCW_NAMESPACE }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download venom binary
        run: |
          curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -o venom
            chmod +x venom
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.4
      - name: compile api
        run: CGO_ENABLED=0 GOOS=linux go build -ldflags "-w" -o ./trackingapi cmd/main.go
      - name: Run tests
        env:
          DBHost: "ip"
          Env: "dev"
        run: |
          ./trackingapi &
          ./venom run tests/test.yaml

  build-feature:
      if: github.event_name == 'workflow_dispatch'
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Log in to Scaleway Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: nologin
            password: ${{ secrets.SCW_SECRET_KEY }}
        - name: Build DEV image
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:feature-${{ github.ref }}
  build-dev:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build DEV image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:dev
      - name: Push DEV image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:dev
  build-prod:
    if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'workflow_dispatch'
    needs:
      - test
      - build-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}
      - name: Build PROD image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
      - name: Push PROD image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REGISTRY_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.ref }}
